# Generated by Django 5.1.6 on 2025-03-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_rename_name_autocar_title_rename_name_business_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocar',
            name='price1',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='autocar',
            name='price2',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='autocar',
            name='price3',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='autocar',
            name='price4',
            field=models.DecimalField(decimal_places=2, default=990, max_digits=10),
        ),
        migrations.AddField(
            model_name='autocar',
            name='sub_content',
            field=models.TextField(default='500', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='price1',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='business',
            name='price2',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='business',
            name='price3',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='business',
            name='price4',
            field=models.DecimalField(decimal_places=2, default=990, max_digits=10),
        ),
        migrations.AddField(
            model_name='business',
            name='sub_content',
            field=models.TextField(default='500', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comic',
            name='price1',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='comic',
            name='price2',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='comic',
            name='price3',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='comic',
            name='price4',
            field=models.DecimalField(decimal_places=2, default=990, max_digits=10),
        ),
        migrations.AddField(
            model_name='comic',
            name='sub_content',
            field=models.TextField(default='900', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competitive_exam',
            name='price1',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='competitive_exam',
            name='price2',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='competitive_exam',
            name='price3',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='competitive_exam',
            name='price4',
            field=models.DecimalField(decimal_places=2, default=990, max_digits=10),
        ),
        migrations.AddField(
            model_name='competitive_exam',
            name='sub_content',
            field=models.TextField(default='900', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entertainment',
            name='price1',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='entertainment',
            name='price2',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='entertainment',
            name='price3',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='entertainment',
            name='price4',
            field=models.DecimalField(decimal_places=2, default=990, max_digits=10),
        ),
        migrations.AddField(
            model_name='entertainment',
            name='sub_content',
            field=models.TextField(default='988', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fashion',
            name='price1',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='fashion',
            name='price2',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='fashion',
            name='price3',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='fashion',
            name='price4',
            field=models.DecimalField(decimal_places=2, default=990, max_digits=10),
        ),
        migrations.AddField(
            model_name='fashion',
            name='sub_content',
            field=models.TextField(default='900', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fitness',
            name='price1',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='fitness',
            name='price2',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='fitness',
            name='price3',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='fitness',
            name='price4',
            field=models.DecimalField(decimal_places=2, default=990, max_digits=10),
        ),
        migrations.AddField(
            model_name='fitness',
            name='sub_content',
            field=models.TextField(default='988', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='health',
            name='price1',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='health',
            name='price2',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='health',
            name='price3',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='health',
            name='price4',
            field=models.DecimalField(decimal_places=2, default=990, max_digits=10),
        ),
        migrations.AddField(
            model_name='health',
            name='sub_content',
            field=models.TextField(default='566', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holiday',
            name='price1',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='holiday',
            name='price2',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='holiday',
            name='price3',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='holiday',
            name='price4',
            field=models.DecimalField(decimal_places=2, default=990, max_digits=10),
        ),
        migrations.AddField(
            model_name='holiday',
            name='sub_content',
            field=models.TextField(default='877', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lifestyles',
            name='price1',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='lifestyles',
            name='price2',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='lifestyles',
            name='price3',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='lifestyles',
            name='price4',
            field=models.DecimalField(decimal_places=2, default=990, max_digits=10),
        ),
        migrations.AddField(
            model_name='lifestyles',
            name='sub_content',
            field=models.TextField(default='900', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magazine',
            name='price1',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='magazine',
            name='price2',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='magazine',
            name='price3',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='magazine',
            name='price4',
            field=models.DecimalField(decimal_places=2, default=990, max_digits=10),
        ),
        migrations.AddField(
            model_name='magazine',
            name='sub_content',
            field=models.TextField(default='900', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='new_arrivals',
            name='price1',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='new_arrivals',
            name='price2',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='new_arrivals',
            name='price3',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='new_arrivals',
            name='price4',
            field=models.DecimalField(decimal_places=2, default=990, max_digits=10),
        ),
        migrations.AddField(
            model_name='new_arrivals',
            name='sub_content',
            field=models.TextField(default='788', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newspaper',
            name='price1',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='newspaper',
            name='price2',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='newspaper',
            name='price3',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='newspaper',
            name='price4',
            field=models.DecimalField(decimal_places=2, default=990, max_digits=10),
        ),
        migrations.AddField(
            model_name='newspaper',
            name='sub_content',
            field=models.TextField(default='566', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popular',
            name='price1',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='popular',
            name='price2',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='popular',
            name='price3',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='popular',
            name='price4',
            field=models.DecimalField(decimal_places=2, default=990, max_digits=10),
        ),
        migrations.AddField(
            model_name='popular',
            name='sub_content',
            field=models.TextField(default='899', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sport',
            name='price1',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='sport',
            name='price2',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='sport',
            name='price3',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='sport',
            name='price4',
            field=models.DecimalField(decimal_places=2, default=990, max_digits=10),
        ),
        migrations.AddField(
            model_name='sport',
            name='sub_content',
            field=models.TextField(default='677', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technology',
            name='price1',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='technology',
            name='price2',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='technology',
            name='price3',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=10),
        ),
        migrations.AddField(
            model_name='technology',
            name='price4',
            field=models.DecimalField(decimal_places=2, default=990, max_digits=10),
        ),
        migrations.AddField(
            model_name='technology',
            name='sub_content',
            field=models.TextField(default='788', max_length=500),
            preserve_default=False,
        ),
    ]
