# Generated by Django 5.1.6 on 2025-03-28 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_rename_total_price_cartitem_item_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='user',
            new_name='reader_user',
        ),
        migrations.RenameField(
            model_name='comic',
            old_name='tile',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='technology',
            old_name='tile',
            new_name='title',
        ),
    ]
